services:
  namenode:
    image: ramonamez/hadoop-namenode:hadoop3.3.1-java8-python3.10
    container_name: namenode
    build: ./namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
      - 8888:8888
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./sync:/sync
    env_file:
      - ./config
    environment:
      - CLUSTER_NAME=test
      - HIVE_HOME=/hive/apache-hive-3.1.3-bin
    deploy: 
      replicas: 1
      placement:
        constraints:
          - node.role==manager

  resourcemanager:
    image: ramonamez/hadoop-resourcemanager:hadoop3.3.1-java8-python3.10
    container_name: resourcemanager
    build: ./resourcemanager
    restart: always
    ports:
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./config
    deploy: 
      replicas: 1
      placement:
        constraints:
          - node.role==manager

  datanode:
    image: ramonamez/hadoop-datanode:hadoop3.3.1-java8-python3.10
    container_name: datanode
    build: ./datanode
    restart: always
    ports:
      - 9864:9864
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./config
    deploy: 
      replicas: 2
      placement:
        constraints:
          - node.role==worker

  nodemanager:
    image: ramonamez/hadoop-nodemanager:hadoop3.3.1-java8-python3.10
    container_name: nodemanager
    build: ./nodemanager
    restart: always
    ports:
      - 8042:8042
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./config
    deploy: 
      replicas: 2
      placement:
        constraints:
          - node.role==worker

  historyserver:
    image: ramonamez/hadoop-historyserver:hadoop3.3.1-java8-python3.10
    container_name: historyserver
    build: ./historyserver
    restart: always
    ports:
      - 8188:8188
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./config

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
